all:
	javac Payable.java Invoice.java Employee.java SalariedEmployee.java HourlyEmployee.java CommissionEmployee.java BasePlusCommissionEmployee.java PayableInterfaceTest.java
	java PayableInterfaceTest

clean:
	rm *.class
